name: NovyXtreme
version: '1.5.7'
main: novyXtreme.NovyXtreme
depend:
  - Vault
  - EconomyPlus

api-version: 1.19
authors: [ Dograffe, parknich ]
description: Main Project for Stargate Remake
commands:
  stcomplete:
    description: Create stargate
    usage: /<command>
  dial:
    description: dial a stargate
    usage: /<command>
  stgo:
    description: sends player to given stargate
    usage: /<command>
  stkeep:
    description: remove all stargates except for given gate
    usage: /<command>
  stlock:
    description:  lock a stargate
    usage: /<command>
  stlist:
    description: lists all stargates
    usage: /<command>
  stremove:
    description: removes given stargate
    usage: /<command>
  streload:
    description: reloads plugin config and database
    usage: /<command>
  stforce:
    description: deactivates all active gates
    usage: /<command>




